[package]
authors = ["Jesus Guzman, Jr. <jesusguzmanjr@icloud.com>"]
edition = "2024"
name = "rust-gpt"
publish = false
repository = "https://github.com/MarzipanClub/rust-gpt"
version = "0.1.0"

# https://dev-doc.rust-lang.org/stable/rustc/lints/listing/index.html#lint-listing
[lints.rust]
let_underscore_drop = "warn"
missing_debug_implementations = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
rust_2024_compatibility = { level = "warn", priority = -1 }
single_use_lifetimes = "warn"
unreachable_pub = "warn"
unused_extern_crates = "deny"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.100"
arrow-array = "56.2.0"
arrow-cast = "56.2.0"
bincode = { version = "2.0.1", features = ["serde"] }
bytes = "1.10.1"
bytesize = "2.1.0"
clap = { version = "4.5.48", features = ["derive"] }
comrak = "0.43.0"
crossbeam-channel = "0.5.15"
ctrlc = "3.5.0"
futures = "0.3.31"
icu_normalizer = "2.0.0"
indexmap = "2.11.4"
itertools = "0.14.0"
parquet = "56.2.0"
rayon = "1.11.0"
regex = "1.12.1"
reqwest = { version = "0.12.23", features = ["stream"] }
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.138"
smallvec = { version = "1.15.1", features = ["serde"] }
tempfile = "3.23.0"
thousands = "0.2.0"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
xdg = "3.0.0"
zstd = "0.13.3"

[dev-dependencies]
criterion = "0.7.0"

[build-dependencies]
cc = "1.2.41"

[[bench]]
harness = false
name = "kernels"
