[workspace]
members = ["common", "language_model", "web"]
resolver = "3"

[workspace.package]
authors = ["Jesus Guzman, Jr. <jesusguzmanjr@icloud.com>"]
edition = "2024"
publish = false
repository = "https://github.com/MarzipanClub/rust-gpt"
version = "0.1.0"

# https://dev-doc.rust-lang.org/stable/rustc/lints/listing/index.html#lint-listing
[workspace.lints.rust]
let_underscore_drop = "warn"
missing_debug_implementations = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
rust_2024_compatibility = { level = "warn", priority = -1 }
unreachable_pub = "warn"
unused_extern_crates = "deny"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"

[workspace.dependencies]
# switch to a released version when https://github.com/vincent-herlemont/native_db/issues/357 is fixed
native_db = { git = "https://github.com/vincent-herlemont/native_db.git", branch = "main" }

anyhow = "1.0.100"
bytesize = "2.1.0"
chrono = "0.4.42"
const_format = "0.2.34"
derive_more = { version = "2.0.1", features = ["display", "from", "from_str"] }
futures = "0.3.21"
nonempty = "0.12.0"
ron = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
thousands = "0.2.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.17"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
uuid = { version = "1.18.1", features = ["v4", "fast-rng", "serde"] }
zeroize = { version = "1.8.2", features = ["zeroize_derive"] }
