export RUST_LOG := env("RUST_LOG", "info")
export CONFIG := env("CONFIG", "dev-config.ron")

# Run the serve in file-watch dev mode
dev:
    #!/usr/bin/env bash
    watchexec \
    --clear \
    --restart \
    --watch . \
    --watch ../language_model/src \
    --watch ../language_model/Cargo.toml \
    --watch ../language_model/build.rs \
    --watch ../Cargo.toml \
    --watch ../Cargo.lock \
    cargo run --bin web